name: 'pymsnotify'
author: "Ayush Kumar"
description: 'A GitHub Action that takes microsoft teams webhook url as input and send notification to teams channel'
branding:
  icon: 'send'
  color: 'blue'
inputs:
  url:
    description: 'teams channel webhook url'
    required: true
  msg:
    description: 'notification message'
    required: true
  title:
    description: 'notification title'
    required: true
  job_status:
    description: 'notification status'
    required: false
  repository:
    description: 'repository name'
    required: false
  run_id:
    description: 'run id'
    required: false

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install Dependencies
      run: pip install -r ${{github.action_path}}/requirements.txt
      shell: bash
    - name: Pass Inputs to Shell
      run: |
              echo "URL=${{ inputs.url }}" >> $GITHUB_ENV
              echo "MSG=${{ inputs.msg }}" >> $GITHUB_ENV
              echo "TITLE=${{ inputs.title }}" >> $GITHUB_ENV
              echo "STATUS=${{ inputs.job_status }}" >> $GITHUB_ENV
              echo "GITHUB_REPOSITORY=${{ inputs.repository }}" >> $GITHUB_ENV
              echo "GITHUB_RUN_ID=${{ inputs.run_id }}" >> $GITHUB_ENV
      shell: bash
    - name: Send notification to specified teams channel
      id: send-notification
      run: python ${{github.action_path}}/src/pymsnotify/__main__.py
      shell: bash