name: Test Action
on: [push]

jobs:
  get-num-square:
    runs-on: ubuntu-latest
    name: Sends notification to teams.
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: send_notification
        uses: ./
        with:
          url: ${{ secrets.TEAMS_URL }}
          content: ${{ github.sha }}
          title: "HELLO_TEAMS"